Dir {
  ArchiveDir ".";
  CacheDir ".";
};

Default {
  Packages::Compress ". gzip";
};

TreeDefault {
  Directory "pool/$(SECTION)/e/ekiben";
};

Tree "dists/stable" {
  Sections "main";
  Architectures "amd64 arm64";
};

APT::FTPArchive::Release {
  Origin "ekiben";
  Label "ekiben";
  Suite "stable";
  Codename "stable";
  Components "main";
  Architectures "amd64 arm64";
  Description "ekiben APT repository";
};
